server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sample?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: 1111
        driver-class-name: com.mysql.cj.jdbc.Driver
